name: VITE MPA Despliegue de Portal a Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.github-pages.output.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el Repositorio
        uses: actions/checkout@v4

      - name: Instalar Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar las Dependencias del Proyecto
        run: npm install --legacy-peer-deps

      - name: Compilar la página para distribución
        run: npm run build
        env:
          DEPLOY_BASE_URL: /gymbodyperfect/

      - name: Asegurar el 404 fallback
        run: cp ./dist/index.html ./dist/404.html

      - name: Configura Github Pages
        uses: actions/configure-pages@v5

      - name: Subir los compilados (artefactos) a GP
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: github-pages
        uses: actions/deploy-pages@v4
